/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Person.Employee.Manager;
import business.Person.Hospital.Doctor;
import business.Person.Restaurant.RestaurantManager;
import business.Role.DayCareRole.ManagerRole;
import business.Role.Hospital.DoctorRole;
import business.Role.Restaurant.RestaurantManagerRole;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chau_
 */
public class AddManagerJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    /**
     * Creates new form manageRestaurantJPanel
     */
    public AddManagerJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        headlineJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        contactInformationLabel = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        contactInformationTextField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        lastNameTextField = new javax.swing.JTextField();
        nameJLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_UserAccount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Password = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headlineJLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        headlineJLabel.setText("Add Manager");
        add(headlineJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 243, 60));

        nameJLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameJLabel.setText("First Name:");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 93, -1, 38));

        idJLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        idJLabel.setText("Gender:");
        add(idJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 77, 38));

        contactInformationLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contactInformationLabel.setText("Contact Information:");
        add(contactInformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 225, 40));

        addressJLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addressJLabel.setText("Address Information:");
        add(addressJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 225, 40));
        add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 310, 38));
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 94, 174, 38));
        add(contactInformationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 310, 38));

        createJButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 233, 49));

        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        add(jButton_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 94, 189, 38));

        nameJLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameJLabel1.setText("Last Name:");
        add(nameJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 93, -1, 38));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 106, 26));
        add(jTextField_UserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 177, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 106, 26));
        add(jTextField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 177, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        
        
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String username = jTextField_UserAccount.getText();
        String password = jTextField_Password.getText();
        
        switch (enterprise.getEnterpriseType()) {
            case DayCareInstitution:
                Manager manager = new Manager();
                manager.setFirstName(firstName);
                manager.setLastName(lastName);
                if(jRadioButton1.isSelected()){manager.setGender(0);}
                else{manager.setGender(1);}
                enterprise.getPersonDirectory().addPerson(manager);
                if(enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(username)){
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, manager, new ManagerRole());
                    JOptionPane.showMessageDialog(null, "Account Created Successfully");
                }       
                break;
            case Hospital:
                Doctor doctor = new Doctor();
                doctor.setFirstName(firstName);
                doctor.setLastName(lastName);
                enterprise.getPersonDirectory().addPerson(doctor);
                if(enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(username)){
                    UserAccount ua = enterprise.getUserAccountDirectory().createUserAccount(username, password, doctor, new DoctorRole());
                    JOptionPane.showMessageDialog(null, "Account Created Successfully");
                }                
                break;
            case Restaurant:
                RestaurantManager rm = new RestaurantManager();
                rm.setFirstName(firstName);
                rm.setLastName(lastName);
                enterprise.getPersonDirectory().addPerson(rm);
                if(enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(username)){
                    UserAccount rmua = enterprise.getUserAccountDirectory().createUserAccount(username, password, rm, new RestaurantManagerRole());
                    JOptionPane.showMessageDialog(null, "Account Created Successfully");
                }
                break;
            default:
                break;
        }       
    }//GEN-LAST:event_createJButtonActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageOrganizationJPanel manageManagerJPanel = (ManageOrganizationJPanel) component;
        manageManagerJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel contactInformationLabel;
    private javax.swing.JTextField contactInformationTextField;
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel headlineJLabel;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField_Password;
    private javax.swing.JTextField jTextField_UserAccount;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel nameJLabel1;
    // End of variables declaration//GEN-END:variables
}
