/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

import business.Business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Chau_
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = business;
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel dtm = (DefaultTreeModel) ecosystemJTree.getModel();
        ArrayList<Network> networkList = system.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        Network network;
        Enterprise enterprise;
        Organization organization;
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) dtm.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i = 0; i < networkList.size (); i ++){
            network = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(network.getNetworkName());
            networks.insert(networkNode, i);
            
            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            for(int j = 0; j < enterpriseList.size(); j ++){
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                for(int k = 0; k < organizationList.size(); k ++){
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }        
        dtm.reload();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        ecosystemJTree = new javax.swing.JTree();
        rightJPanel = new javax.swing.JPanel();
        headlineJLabel = new javax.swing.JLabel();
        selectNodeJLabel = new javax.swing.JLabel();
        JButton_DayCare = new javax.swing.JButton();
        JButton_Restaurant = new javax.swing.JButton();
        JButton_ManageNetwork = new javax.swing.JButton();
        JButton_ManageEnterprise = new javax.swing.JButton();
        JButton_ManageEnterpriseAdmin = new javax.swing.JButton();
        jButton_ManageHospital = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane.setDividerLocation(150);

        ecosystemJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                ecosystemJTreeValueChanged(evt);
            }
        });
        ScrollPane.setViewportView(ecosystemJTree);

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(leftJPanel);

        headlineJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        headlineJLabel.setText("Selected Node:");

        selectNodeJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectNodeJLabel.setText("<View_Selected_Node>");

        JButton_DayCare.setText("Manage Day Care Institution");
        JButton_DayCare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_DayCareActionPerformed(evt);
            }
        });

        JButton_Restaurant.setText("Manage  Restaurant");
        JButton_Restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_RestaurantActionPerformed(evt);
            }
        });

        JButton_ManageNetwork.setText("Manage Network");
        JButton_ManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ManageNetworkActionPerformed(evt);
            }
        });

        JButton_ManageEnterprise.setText("Manage Enterprise");
        JButton_ManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ManageEnterpriseActionPerformed(evt);
            }
        });

        JButton_ManageEnterpriseAdmin.setText("Manage Enterprise Admin");
        JButton_ManageEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ManageEnterpriseAdminActionPerformed(evt);
            }
        });

        jButton_ManageHospital.setText("Manage Hospital");
        jButton_ManageHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ManageHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightJPanelLayout = new javax.swing.GroupLayout(rightJPanel);
        rightJPanel.setLayout(rightJPanelLayout);
        rightJPanelLayout.setHorizontalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJPanelLayout.createSequentialGroup()
                .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(headlineJLabel))
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JButton_DayCare, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButton_Restaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButton_ManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButton_ManageEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButton_ManageEnterpriseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ManageHospital)))
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(selectNodeJLabel)))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        rightJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JButton_Restaurant, jButton_ManageHospital});

        rightJPanelLayout.setVerticalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(headlineJLabel)
                .addGap(54, 54, 54)
                .addComponent(selectNodeJLabel)
                .addGap(59, 59, 59)
                .addComponent(JButton_ManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButton_ManageEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButton_ManageEnterpriseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButton_DayCare, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButton_Restaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ManageHospital)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        rightJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JButton_Restaurant, jButton_ManageHospital});

        jSplitPane.setRightComponent(rightJPanel);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ecosystemJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_ecosystemJTreeValueChanged
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) ecosystemJTree.getLastSelectedPathComponent();
        if(selectedNode != null){
            selectNodeJLabel.setText(selectedNode.toString());
        }       
    }//GEN-LAST:event_ecosystemJTreeValueChanged

    private void JButton_ManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ManageNetworkActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system); 
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_JButton_ManageNetworkActionPerformed

    private void JButton_DayCareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_DayCareActionPerformed
        // TODO add your handling code here:
//        ManageManagerJPanel manageManagerJPanel = new ManageManagerJPanel(userProcessContainer, system); 
//        userProcessContainer.add("ManageManagerJPanel", manageManagerJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_JButton_DayCareActionPerformed

    private void JButton_RestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_RestaurantActionPerformed
        // TODO add your handling code here:
        ManageRestaurantJPanel manageRestaurantJPanel = new ManageRestaurantJPanel(userProcessContainer, system); 
        userProcessContainer.add("ManageRestaurantJPanel", manageRestaurantJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_JButton_RestaurantActionPerformed

    private void JButton_ManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ManageEnterpriseActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, system); 
        userProcessContainer.add("ManageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_JButton_ManageEnterpriseActionPerformed

    private void JButton_ManageEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ManageEnterpriseAdminActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, system); 
        userProcessContainer.add("ManageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_JButton_ManageEnterpriseAdminActionPerformed

    private void jButton_ManageHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ManageHospitalActionPerformed
        // TODO add your handling code here:
        ManageHospitalJPanel manageHospitalJPanel = new ManageHospitalJPanel(userProcessContainer, system); 
        userProcessContainer.add("manageHospitalJPanel", manageHospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton_ManageHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_DayCare;
    private javax.swing.JButton JButton_ManageEnterprise;
    private javax.swing.JButton JButton_ManageEnterpriseAdmin;
    private javax.swing.JButton JButton_ManageNetwork;
    private javax.swing.JButton JButton_Restaurant;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTree ecosystemJTree;
    private javax.swing.JLabel headlineJLabel;
    private javax.swing.JButton jButton_ManageHospital;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JLabel selectNodeJLabel;
    // End of variables declaration//GEN-END:variables
}
