/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

import business.Business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.HospitalEnterprise;
import business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chau_
 */
public class ManageHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospitalJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public ManageHospitalJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateNetworkJComboBox();
    }

    public void populateNetworkJComboBox() {
        networkJComboBox.removeAllItems();
        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }

    private void populateTable(Network network) {
        DefaultTableModel dtm = (DefaultTableModel) hospitalJTable.getModel();
        dtm.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)) {
                Object[] row = new Object[3];
                row[0] = enterprise;
                row[1] = enterprise.getEnterpriseType();
                row[2] = network.getNetworkName();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkJComboBox = new javax.swing.JComboBox();
        managerJScrollPane = new javax.swing.JScrollPane();
        hospitalJTable = new javax.swing.JTable();
        viewDetailJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        headlineJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 127, 245, 40));

        hospitalJTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hospitalJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital  Name", "Hospital ID", "Network"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        managerJScrollPane.setViewportView(hospitalJTable);

        add(managerJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 193, 682, 299));

        viewDetailJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewDetailJButton.setText("View Details");
        viewDetailJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailJButtonActionPerformed(evt);
            }
        });
        add(viewDetailJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 521, 215, 66));

        removeJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 521, 172, 66));

        backJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 521, 172, 66));

        headlineJLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        headlineJLabel.setText("Manage Hospital Work Area");
        add(headlineJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 34, 347, 49));

        nameJLabel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        nameJLabel.setText("Select a Network Name:");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 127, 287, 48));
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network)networkJComboBox.getSelectedItem();
        populateTable(network);
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void viewDetailJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailJButtonActionPerformed
        int selectRow = hospitalJTable.getSelectedRow();
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        HospitalEnterprise hospitalEnterprise = (HospitalEnterprise)hospitalJTable.getValueAt(selectRow,0);
        ViewHospitalJPanel viewHospitalJPanel = new ViewHospitalJPanel(userProcessContainer, hospitalEnterprise);
        userProcessContainer.add("viewHospitalJPanel", viewHospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDetailJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        int row = hospitalJTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        HospitalEnterprise s = (HospitalEnterprise) hospitalJTable.getValueAt(row, 0);
        Network network = (Network)networkJComboBox.getSelectedItem();
        network.getEnterpriseDirectory().deleteEnterprise(s);
        populateTable(network);
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];

        AdminWorkAreaJPanel sysAdminwjp = (AdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel headlineJLabel;
    private javax.swing.JTable hospitalJTable;
    private javax.swing.JScrollPane managerJScrollPane;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JButton removeJButton;
    private javax.swing.JButton viewDetailJButton;
    // End of variables declaration//GEN-END:variables
}
