/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

import business.Business.EcoSystem;
import java.text.DecimalFormat;
import javax.swing.JPanel;

/**
 *
 * @author hao
 */
public class ViewReports extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form ViewReports
     */
    public ViewReports(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateLable();
    }
    private void populateLable(){
        jLabel_TotalEnterprise.setText(String.valueOf(system.caculateTotalEnterprise()));
        jLabel_Network.setText(String.valueOf(system.caculateTotalNetwork()));
        jLabel_TotalPerson.setText(String.valueOf(system.caculateTotalPerson()));
        jLabel_TotalChild.setText(String.valueOf(system.caculateTotalChild()));
        jLabel_TotalRestaurants.setText(String.valueOf(system.caculateTotalRestaurant()));
        jLabel_TotalHospital.setText(String.valueOf(system.caculateTotalHospital()));
        jLabel_TotalDayCare.setText(String.valueOf(system.caculateTotalDayCare()));
        int a = system.caculateTotalChild();
        double b = ((double)a/30) * 100;
        DecimalFormat df = new DecimalFormat("###.00");
        jLabel_ChildEducationRate.setText(String.valueOf(df.format(b) +"%"));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_TotalEnterprise = new javax.swing.JLabel();
        jLabel_Network = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_TotalPerson = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_TotalChild = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_TotalDayCare = new javax.swing.JLabel();
        jLabel_TotalRestaurants = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_TotalHospital = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_ChildEducationRate = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Reports");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Total Enterprise:");

        jLabel_TotalEnterprise.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_TotalEnterprise.setText("jLabel3");

        jLabel_Network.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_Network.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Total Network:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Total Person:");

        jLabel_TotalPerson.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_TotalPerson.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Total Child:");

        jLabel_TotalChild.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_TotalChild.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Total Day Care Institution:");

        jLabel_TotalDayCare.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_TotalDayCare.setText("jLabel3");

        jLabel_TotalRestaurants.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_TotalRestaurants.setText("jLabel3");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Total Restaurants:");

        jLabel_TotalHospital.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_TotalHospital.setText("jLabel3");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Total Hospitals:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Child Education Rate:");

        jLabel_ChildEducationRate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_ChildEducationRate.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Network)
                                    .addComponent(jLabel_TotalEnterprise)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_TotalPerson)
                                    .addComponent(jLabel_TotalChild)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_TotalDayCare))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_TotalRestaurants))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_TotalHospital))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_ChildEducationRate)))))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Network)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_TotalEnterprise))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_TotalDayCare))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_TotalRestaurants))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel_TotalHospital))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_TotalPerson))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_TotalChild))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_ChildEducationRate))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ChildEducationRate;
    private javax.swing.JLabel jLabel_Network;
    private javax.swing.JLabel jLabel_TotalChild;
    private javax.swing.JLabel jLabel_TotalDayCare;
    private javax.swing.JLabel jLabel_TotalEnterprise;
    private javax.swing.JLabel jLabel_TotalHospital;
    private javax.swing.JLabel jLabel_TotalPerson;
    private javax.swing.JLabel jLabel_TotalRestaurants;
    // End of variables declaration//GEN-END:variables
}
