/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

/**
 *
 * @author Chau_
 */
public class ViewManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewManagerJPanel
     */
    public ViewManagerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headLineJLabel = new javax.swing.JLabel();
        dayCareCenterNameJLabel = new javax.swing.JLabel();
        dayCareCenterJTextField = new javax.swing.JTextField();
        nameJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        contactJLabel = new javax.swing.JLabel();
        contactInformationJTextField = new javax.swing.JTextField();
        addressJLabel = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headLineJLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headLineJLabel.setText("Manager Information");
        add(headLineJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 66, 280, 54));

        dayCareCenterNameJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dayCareCenterNameJLabel.setText("Day Care Center Name：");
        add(dayCareCenterNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 172, -1, -1));
        add(dayCareCenterJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 177, 248, -1));

        nameJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameJLabel.setText("Name：");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 225, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 230, 248, -1));

        contactJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        contactJLabel.setText("Contact Information:");
        add(contactJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 268, -1, -1));
        add(contactInformationJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 273, 248, -1));

        addressJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addressJLabel.setText("Address:");
        add(addressJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 311, -1, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 316, 248, -1));

        backButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        backButton.setText("<<back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 418, -1, -1));

        updateButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        updateButton.setText("update");
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 418, 115, -1));

        saveButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        saveButton.setText("save");
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 418, 115, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField contactInformationJTextField;
    private javax.swing.JLabel contactJLabel;
    private javax.swing.JTextField dayCareCenterJTextField;
    private javax.swing.JLabel dayCareCenterNameJLabel;
    private javax.swing.JLabel headLineJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
