/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Restaurant;

import business.Enterprise.Enterprise;
import business.Enterprise.RestaurantEnterprise;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chau_
 */
public class RestaurantManagerWorkArea extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    RestaurantEnterprise enterprise;
    /**
     * Creates new form RestaurantManagerWorkArea
     */
    public RestaurantManagerWorkArea(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise =(RestaurantEnterprise)enterprise;
        nameJLabel.setText(enterprise.getName());
//      populate();
    }

//public void populateTable(){
//        DefaultTableModel model = (DefaultTableModel)jTable_Order.getModel();
//        
//        model.setRowCount(0);
//        
//        for(WorkRequest request : .getWorkQueue().getWorkRequestList()){
//            Object[] row = new Object[4];
//            row[0] = request;
//            row[1] = request.getSender().getEmployee().getName();
//            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
//            row[3] = request.getStatus();
//            
//            model.addRow(row);
//        }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headLineJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        restaurantNameJLabel = new javax.swing.JLabel();
        jButton_updateBasicInformation = new javax.swing.JButton();
        jButton_updateMenu = new javax.swing.JButton();
        jScrollPane_Order = new javax.swing.JScrollPane();
        jTable_Order = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        headLineJLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headLineJLabel.setText("Restaurant Manager WorkArea");

        nameJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameJLabel.setText("<Restaurant Name>");

        restaurantNameJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        restaurantNameJLabel.setText("Restaurant Name:");

        jButton_updateBasicInformation.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_updateBasicInformation.setText("Update Basic Information");
        jButton_updateBasicInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateBasicInformationActionPerformed(evt);
            }
        });

        jButton_updateMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_updateMenu.setText("Update  the Menu");
        jButton_updateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateMenuActionPerformed(evt);
            }
        });

        jTable_Order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Custoner Name", "Address", "Contact Information", "Amount"
            }
        ));
        jScrollPane_Order.setViewportView(jTable_Order);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Order Table:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton_updateBasicInformation)
                        .addGap(126, 126, 126)
                        .addComponent(jButton_updateMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(restaurantNameJLabel)
                                .addGap(63, 63, 63)
                                .addComponent(nameJLabel))
                            .addComponent(headLineJLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(headLineJLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel)
                    .addComponent(restaurantNameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_updateBasicInformation)
                    .addComponent(jButton_updateMenu))
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateBasicInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateBasicInformationActionPerformed
        // TODO add your handling code here:
        UpdateBasicInformationJPanel updateBasicInformationJPanel= new UpdateBasicInformationJPanel(userProcessContainer, enterprise); 
        userProcessContainer.add("updateBasicInformationJPanel", updateBasicInformationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);     
    }//GEN-LAST:event_jButton_updateBasicInformationActionPerformed

    private void jButton_updateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateMenuActionPerformed
        // TODO add your handling code here:
        UpdateMenuJPanel UpdateMenuJPanel= new UpdateMenuJPanel(userProcessContainer, enterprise); 
        userProcessContainer.add("updateBasicInformationJPanel", UpdateMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);   
    }//GEN-LAST:event_jButton_updateMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headLineJLabel;
    private javax.swing.JButton jButton_updateBasicInformation;
    private javax.swing.JButton jButton_updateMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane_Order;
    private javax.swing.JTable jTable_Order;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel restaurantNameJLabel;
    // End of variables declaration//GEN-END:variables
}
