/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Restaurant;

import business.Enterprise.RestaurantEnterprise;
import business.Menu.Menu;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Chau_
 */
public class UpdateMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form updateMenuJPanel
     */
    private Menu menu;
    private JPanel userProcessContainer;
    public UpdateMenuJPanel(JPanel userProcessContainer,RestaurantEnterprise enterprise) {
        initComponents();
//        this.menu = enterprise.getMenu();
        this.userProcessContainer = userProcessContainer;
        nameTextField.setText(menu.getName());
        stapleFoodJTextField.setText(menu.getStapleFood());
        fruitJTextField.setText(menu.getFruit());
        beverageTextField.setText(menu.getBeverage());
        calorieJTextField.setText(menu.getTotalCalorie()+"");
        if(menu.isAginomoto()){
            yesJRadioButton.setSelected(true);
        }else{
            noJRadioButton.setSelected(true);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headLineJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        stapleFoodJLabel = new javax.swing.JLabel();
        stapleFoodJTextField = new javax.swing.JTextField();
        fruitJLabel = new javax.swing.JLabel();
        fruitJTextField = new javax.swing.JTextField();
        calorieJLabel = new javax.swing.JLabel();
        calorieJTextField = new javax.swing.JTextField();
        beverageTextField = new javax.swing.JTextField();
        beverageJLabel = new javax.swing.JLabel();
        aginomotoJLabel = new javax.swing.JLabel();
        yesJRadioButton = new javax.swing.JRadioButton();
        noJRadioButton = new javax.swing.JRadioButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();

        headLineJLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headLineJLabel.setText("Menu Information");

        nameJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameJLabel.setText("Name:");

        nameTextField.setEditable(false);

        stapleFoodJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        stapleFoodJLabel.setText("Staple Food:");

        stapleFoodJTextField.setEditable(false);

        fruitJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fruitJLabel.setText("Fruit:");

        fruitJTextField.setEditable(false);

        calorieJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        calorieJLabel.setText("Total Calorie:");

        calorieJTextField.setEditable(false);

        beverageTextField.setEditable(false);

        beverageJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        beverageJLabel.setText("Beverage:");

        aginomotoJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        aginomotoJLabel.setText("Aginomoto:");

        yesJRadioButton.setText("Yes");

        noJRadioButton.setText("No");

        jButton_Update.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Save.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.setEnabled(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Back.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton_Back.setText("<<Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stapleFoodJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fruitJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(stapleFoodJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fruitJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(beverageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calorieJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aginomotoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calorieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(beverageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yesJRadioButton)
                                        .addGap(33, 33, 33)
                                        .addComponent(noJRadioButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButton_Back)
                        .addGap(128, 128, 128)
                        .addComponent(jButton_Update)
                        .addGap(139, 139, 139)
                        .addComponent(jButton_Save))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headLineJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(606, 606, 606)))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {beverageTextField, fruitJTextField, nameTextField, stapleFoodJTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(headLineJLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stapleFoodJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stapleFoodJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fruitJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fruitJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beverageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beverageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calorieJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calorieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aginomotoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesJRadioButton)
                    .addComponent(noJRadioButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Back)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_Save))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {beverageTextField, fruitJTextField, nameTextField, stapleFoodJTextField});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        nameTextField.setEditable(true);
        stapleFoodJTextField.setEditable(true);
        fruitJTextField.setEditable(true);
        beverageTextField.setEditable(true);
        calorieJTextField.setEditable(true);
        jButton_Save.setEnabled(true);
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        menu.setName(nameTextField.getText());
        menu.setBeverage(beverageTextField.getText());
        menu.setFruit(fruitJTextField.getText());
        menu.setStapleFood(stapleFoodJTextField.getText());
        menu.setTotalCalorie(Integer.parseInt(calorieJTextField.getText()));   
        jButton_Save.setEnabled(false);
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RestaurantManagerWorkArea manageProductCatalogJPanel = (RestaurantManagerWorkArea) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aginomotoJLabel;
    private javax.swing.JLabel beverageJLabel;
    private javax.swing.JTextField beverageTextField;
    private javax.swing.JLabel calorieJLabel;
    private javax.swing.JTextField calorieJTextField;
    private javax.swing.JLabel fruitJLabel;
    private javax.swing.JTextField fruitJTextField;
    private javax.swing.JLabel headLineJLabel;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton noJRadioButton;
    private javax.swing.JLabel stapleFoodJLabel;
    private javax.swing.JTextField stapleFoodJTextField;
    private javax.swing.JRadioButton yesJRadioButton;
    // End of variables declaration//GEN-END:variables
}
