/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ParentsRole;

import business.Customer.Child;
import business.Customer.Parents;
import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.TeacherRole.UpdateTeacherInformationJPanel;

/**
 *
 * @author Chau_
 */
public class ParentsWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    /**
     * Creates new form parentsWorkAreaJPanel
     */
    public ParentsWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        jLabelIcon.setIcon(new javax.swing.ImageIcon("icon.jpg"));
    }

    public void populateComboBox()
    {
        
    }
    
    public void populateTable()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headlineJLabel = new javax.swing.JLabel();
        parentsNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        childrenNameLabel = new javax.swing.JLabel();
        selectChildrenJCombox = new javax.swing.JComboBox();
        manageParentsInformationJButton = new javax.swing.JButton();
        addCourseJButton = new javax.swing.JButton();
        checkoutJButton = new javax.swing.JButton();
        checkinJButton = new javax.swing.JButton();
        jLabelIcon = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headlineJLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        headlineJLabel.setText("Parents Work Area");
        add(headlineJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, 364, 68));

        parentsNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        parentsNameLabel.setText("Parents Name :");
        add(parentsNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 166, 28));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 104, 161, 33));

        childrenNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        childrenNameLabel.setText("Children:");
        add(childrenNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 166, 28));

        add(selectChildrenJCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 166, 167, -1));

        manageParentsInformationJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageParentsInformationJButton.setText("Manage Profile:");
        manageParentsInformationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageParentsInformationJButtonActionPerformed(evt);
            }
        });
        add(manageParentsInformationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 386, 44));

        addCourseJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addCourseJButton.setText("Select a Course");
        addCourseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseJButtonActionPerformed(evt);
            }
        });
        add(addCourseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 386, 44));

        checkoutJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkoutJButton.setText("Check out");
        checkoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutJButtonActionPerformed(evt);
            }
        });
        add(checkoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, 77));

        checkinJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinJButton.setText("Check In");
        checkinJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinJButtonActionPerformed(evt);
            }
        });
        add(checkinJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, 79));
        add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 150, 151));
    }// </editor-fold>//GEN-END:initComponents

    private void manageParentsInformationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageParentsInformationJButtonActionPerformed
        // TODO add your handling code here:
        ParentsInformationJPanel parentsInformationJPanel = new ParentsInformationJPanel(userProcessContainer, userAccount); 
        userProcessContainer.add("ParentsInformationJPanel", parentsInformationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageParentsInformationJButtonActionPerformed

    private void addCourseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseJButtonActionPerformed
        // TODO add your handling code here:
        AddCourseJPanel addCourseJPanel = new AddCourseJPanel(userProcessContainer, enterprise); 
        userProcessContainer.add("AddCourseJPanel", addCourseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addCourseJButtonActionPerformed

    private void checkinJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinJButtonActionPerformed
        // TODO add your handling code here:
        userAccount.getPerson().setStatus(true);
    }//GEN-LAST:event_checkinJButtonActionPerformed

    private void checkoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutJButtonActionPerformed
        // TODO add your handling code here:
        userAccount.getPerson().setStatus(false);
    }//GEN-LAST:event_checkoutJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseJButton;
    private javax.swing.JButton checkinJButton;
    private javax.swing.JButton checkoutJButton;
    private javax.swing.JLabel childrenNameLabel;
    private javax.swing.JLabel headlineJLabel;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JButton manageParentsInformationJButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel parentsNameLabel;
    private javax.swing.JComboBox selectChildrenJCombox;
    // End of variables declaration//GEN-END:variables
}
