/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ParentsRole;

/**
 *
 * @author Chau_
 */
public class UpdateChildInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form updateChildInformationJPanel
     */
    public UpdateChildInformationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headlineJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        statusJLabel = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        statusJComboBox = new javax.swing.JComboBox<>();
        nameJLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headlineJLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headlineJLabel.setText("Update Child Information");
        add(headlineJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 32, 310, 60));

        nameJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameJLabel.setText("Age:");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 212, 142, 38));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 139, 329, 38));
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 212, 329, 38));

        statusJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        statusJLabel.setText("Status:");
        add(statusJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 366, 225, 40));

        saveJButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 512, 233, 49));

        updateJButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });
        add(updateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 512, 233, 49));

        add(statusJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 367, 329, 40));

        nameJLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameJLabel1.setText("Name:");
        add(nameJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 147, 142, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel headlineJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel nameJLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JComboBox<String> statusJComboBox;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
