/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.TeacherRole;

import business.CourseOffering.CourseOffering;
import business.Enterprise.DayCareEnterprise;
import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.Person.Employee.Teacher;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chau_
 */
public class TeacherWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private DayCareEnterprise enterprise;
    /**
     * Creates new form teacherWorkAreaJPanel
     */
    public TeacherWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = (DayCareEnterprise) enterprise;
        jLabel2.setText(enterprise.getName());
        jLabel3.setText(account.getPerson().getFirstName() + " " + account.getPerson().getLastName());
        populateTable();
    }
    
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) jTableSchedule.getModel();
        model.setRowCount(0);
        for (CourseOffering co : enterprise.getCourseOfferingSchedule().getCourseOfferingList())
        {
            if(co.getTeacher() == (Teacher) account.getPerson())
            {
                Object[] row = new Object[4];
                row[0] = co;
                row[1] = co.getStartTime();
                row[2] = co.getEndTime();
                row[3] = co.getChildNum();
                
                model.addRow(row);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headlineJLabel = new javax.swing.JLabel();
        parentsNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        statusJLabel = new javax.swing.JLabel();
        manageParentsInformationJButton = new javax.swing.JButton();
        checkinJButton = new javax.swing.JButton();
        checkoutJButton1 = new javax.swing.JButton();
        statusLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSchedule = new javax.swing.JTable();
        jButtonViewDetails = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headlineJLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        headlineJLabel.setText("Teacher Work Area");
        add(headlineJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 27, 364, 68));

        parentsNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        parentsNameLabel.setText("Teacher Name :");
        add(parentsNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 129, 166, 28));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 124, 161, 33));

        statusJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add(statusJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 190, 161, 33));

        manageParentsInformationJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageParentsInformationJButton.setText("Update My Information");
        manageParentsInformationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageParentsInformationJButtonActionPerformed(evt);
            }
        });
        add(manageParentsInformationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 386, 44));

        checkinJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinJButton.setText("Check In");
        add(checkinJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 79));

        checkoutJButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkoutJButton1.setText("Check out");
        add(checkoutJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, 77));

        statusLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statusLabel1.setText("Status:");
        add(statusLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 100, 28));

        jLabel1.setText("DayCare Center Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseName", "Start Time", "End Time", "Student Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSchedule);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 660, 210));

        jButtonViewDetails.setText("View Details");
        jButtonViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewDetailsActionPerformed(evt);
            }
        });
        add(jButtonViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageParentsInformationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageParentsInformationJButtonActionPerformed
        // TODO add your handling code here:
        UpdateTeacherInformationJPanel updateTeacherInformationJPanel = new UpdateTeacherInformationJPanel(userProcessContainer, account); 
        userProcessContainer.add("UpdateTeacherInformationJPanel", updateTeacherInformationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageParentsInformationJButtonActionPerformed

    private void jButtonViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableSchedule.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row first!");
            return;
        }
        else
        {
            CourseOffering co = (CourseOffering) jTableSchedule.getValueAt(selectedRow, 0);
            ViewDetailsJPanel viewDetailsJPanel = new ViewDetailsJPanel(userProcessContainer, co);
            userProcessContainer.add("ViewDetailsJPanel", viewDetailsJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jButtonViewDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkinJButton;
    private javax.swing.JButton checkoutJButton1;
    private javax.swing.JLabel headlineJLabel;
    private javax.swing.JButton jButtonViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSchedule;
    private javax.swing.JButton manageParentsInformationJButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel parentsNameLabel;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JLabel statusLabel1;
    // End of variables declaration//GEN-END:variables

}
