/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Register;

import business.Business.EcoSystem;
import business.Customer.Child;
import business.Customer.Parents;
import business.Enterprise.Enterprise;
import business.Person.DateOfBirth;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hao
 */
public class ChildrenRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChildrenRegistrationJPanel
     */
    private JPanel userProcessContainer;
    private Parents parents;
    private Enterprise enterprise;
    public ChildrenRegistrationJPanel(JPanel userProcessContainer, Enterprise enterprise, Parents parents) {
        initComponents();
        this.parents = parents;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldChildrenFirstName = new javax.swing.JTextField();
        jTextFieldChildrenLastName = new javax.swing.JTextField();
        jTextFieldDobMonth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonBoy = new javax.swing.JRadioButton();
        jRadioButtonGirl = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonAddAnother = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDobDay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDobYear = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 149, -1, -1));

        jLabel2.setText("Last Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 188, -1, -1));

        jLabel3.setText("Date of Birth:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel4.setText("Gender:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 272, -1, -1));
        add(jTextFieldChildrenFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 146, 150, -1));
        add(jTextFieldChildrenLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 185, 150, -1));

        jTextFieldDobMonth.setText("MM");
        add(jTextFieldDobMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 228, 40, -1));

        jLabel6.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel6.setText("Children Registration");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 41, -1, -1));

        buttonGroup1.add(jRadioButtonBoy);
        jRadioButtonBoy.setText("Boy");
        add(jRadioButtonBoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        buttonGroup1.add(jRadioButtonGirl);
        jRadioButtonGirl.setText("Girl");
        jRadioButtonGirl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGirlActionPerformed(evt);
            }
        });
        add(jRadioButtonGirl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jButtonAddAnother.setText("Add Another Child");
        jButtonAddAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAnotherActionPerformed(evt);
            }
        });
        add(jButtonAddAnother, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        jLabel5.setText("/");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jTextFieldDobDay.setText("DD");
        add(jTextFieldDobDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 40, -1));

        jLabel7.setText("/");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jTextFieldDobYear.setText("YYYY");
        add(jTextFieldDobYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonGirlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGirlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGirlActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        Child child = new Child();
        enterprise.getPersonDirectory().addPerson(child);
//        System.out.println(enterprise.getPersonDirectory().getPersonList());
        child.setParents(parents);
        child.setFirstName(jTextFieldChildrenFirstName.getText());
        child.setLastName(jTextFieldChildrenLastName.getText());
        DateOfBirth dob = new DateOfBirth();
        dob.setMonth(Integer.parseInt(jTextFieldDobMonth.getText()));
        dob.setDay(Integer.parseInt(jTextFieldDobDay.getText()));
        dob.setYear(Integer.parseInt(jTextFieldDobYear.getText()));
        child.setDob(dob);
        if(jRadioButtonBoy.isSelected())
        {
            child.setGender(0);
        }
        else
        {
            child.setGender(1);
        }
        JOptionPane.showMessageDialog(null, "Information successfully saved!");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonAddAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAnotherActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(null, "Do you want to add another child?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(choose == JOptionPane.YES_OPTION)
        {
            jTextFieldChildrenFirstName.setText("");
            jTextFieldChildrenLastName.setText("");
            jTextFieldDobDay.setText("DD");
            jTextFieldDobMonth.setText("MM");
            jTextFieldDobYear.setText("YYYY");
            jRadioButtonBoy.setSelected(false);
            jRadioButtonGirl.setSelected(false);
        }
        else
        {
            return;
        }
    }//GEN-LAST:event_jButtonAddAnotherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAddAnother;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonBoy;
    private javax.swing.JRadioButton jRadioButtonGirl;
    private javax.swing.JTextField jTextFieldChildrenFirstName;
    private javax.swing.JTextField jTextFieldChildrenLastName;
    private javax.swing.JTextField jTextFieldDobDay;
    private javax.swing.JTextField jTextFieldDobMonth;
    private javax.swing.JTextField jTextFieldDobYear;
    // End of variables declaration//GEN-END:variables
}
