/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Register;

import business.Business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hao
 */
public class RegisterWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form RegisterWorkAreaJPanel
     */
    public RegisterWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateComboBox();
    }
    
    private void populateComboBox(){
        jComboBox_Network.removeAllItems();
        for(Network network : system.getNetworkList()){
            jComboBox_Network.addItem(network);
        }
    }
    
    private void populateTable(Network network){
        DefaultTableModel dtm = (DefaultTableModel)jTable_DayCareTable.getModel();
        dtm.setRowCount(0);
        try {
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.DayCareInstitution)){
                    Object[] row = new Object[3];
                    row[0] = enterprise;
                    row[1] = enterprise.getSupportedRole();
                    row[2] = enterprise.getId();
                    dtm.addRow(row);
                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DayCareTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Network = new javax.swing.JComboBox();
        jButton_Choose = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_ViewDetial = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_DayCareTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day Care Name", "Location", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTable_DayCareTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 120, 679, 224));

        jLabel1.setText("Please Select Your Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 59, -1, -1));

        jComboBox_Network.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NetworkActionPerformed(evt);
            }
        });
        add(jComboBox_Network, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 56, 70, -1));

        jButton_Choose.setText("Choose ");
        jButton_Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChooseActionPerformed(evt);
            }
        });
        add(jButton_Choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 395, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 480, -1, -1));

        jButton_ViewDetial.setText("View Detial");
        jButton_ViewDetial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewDetialActionPerformed(evt);
            }
        });
        add(jButton_ViewDetial, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_NetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NetworkActionPerformed
        // TODO add your handling code here:
        Network network = (Network)jComboBox_Network.getSelectedItem();
        populateTable(network);
    }//GEN-LAST:event_jComboBox_NetworkActionPerformed

    private void jButton_ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChooseActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_DayCareTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!");
            return;
        }
        
        Enterprise enterprise = (Enterprise) jTable_DayCareTable.getValueAt(selectedRow, 0);
        RegisterUserAccount registerUserAccount = new RegisterUserAccount(userProcessContainer, enterprise); 
        userProcessContainer.add("RegisterUserAccount", registerUserAccount);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton_ChooseActionPerformed

    private void jButton_ViewDetialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewDetialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ViewDetialActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        ManageOrganizationJPanel manageManagerJPanel = (ManageOrganizationJPanel) component;
//        manageManagerJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Choose;
    private javax.swing.JButton jButton_ViewDetial;
    private javax.swing.JComboBox jComboBox_Network;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DayCareTable;
    // End of variables declaration//GEN-END:variables
}
