/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Nutritionist;

import business.Business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.RestaurantEnterprise;
import business.Menu.Menu;
import business.Network.Network;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.RestaurantWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chau_
 */
public class OrderFoodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderFoodJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;


    public OrderFoodJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
      initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.account = account;
        this.business = business;
//        populatedJComBox();
        populateRestaurantComboBox();
    }
    
    private void populateRestaurantComboBox(){
        jComboBox_Restaurant.removeAllItems();
        for(Network network : business.getNetworkList()){
            if(network == enterprise.getNetwork()){
                for(Enterprise en : network.getEnterpriseDirectory().getEnterpriseList()){
                    if(en.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.Restaurant.getValue())){
                        jComboBox_Restaurant.addItem(en);
                    }
                }
            }
        }                     
    }
    private void populateMenuTable(RestaurantEnterprise enterprise){
        DefaultTableModel dtm = (DefaultTableModel) jTable_Menu.getModel();
        dtm.setRowCount(0);
        try {
            for(Menu m : enterprise.getMenuDirectory().getMenus()){
            Object[] row = new Object[4];
                row[0] = m;
                row[1] = m.getTotalCalorie();
                row[2] = m.getFruit();
                row[3] = m.getStapleFood();
                dtm.addRow(row);
        }
        } catch (Exception e) {
        }
    }
    
    
    
//    public void populatedJComBox() {
//        jComboBox_NetWorkArea.removeAll();
//        for (Network network : business.getNetworkList()) {
//            jComboBox_NetWorkArea.addItem(network);
//        }
//    }
    
        private void populateTable(Network network) {
        DefaultTableModel dtm = (DefaultTableModel) jTable_Restaurant.getModel();
        dtm.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Restaurant)) {
                Object[] row = new Object[2];
                row[0] = enterprise;
                row[1] = enterprise.getEnterpriseType();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_hint = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea_Message = new javax.swing.JTextArea();
        jScrollPane_hospital = new javax.swing.JScrollPane();
        jTable_Restaurant = new javax.swing.JTable();
        jButton_Back = new javax.swing.JButton();
        jButton_Send = new javax.swing.JButton();
        jLabel_Message = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Menu = new javax.swing.JTable();
        jComboBox_Restaurant = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel_hint.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_hint.setText("Choose  a Restaurant :");

        jTextArea_Message.setColumns(20);
        jTextArea_Message.setRows(5);
        jScrollPane.setViewportView(jTextArea_Message);

        jTable_Restaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant Name", "Type"
            }
        ));
        jScrollPane_hospital.setViewportView(jTable_Restaurant);

        jButton_Back.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton_Back.setText("<<Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jButton_Send.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton_Send.setText("Send>>");
        jButton_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SendActionPerformed(evt);
            }
        });

        jLabel_Message.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Message.setText("Message");

        jTable_Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu Name", "Total Calorie", "Fruit", "Staple Food"
            }
        ));
        jScrollPane3.setViewportView(jTable_Menu);

        jComboBox_Restaurant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RestaurantActionPerformed(evt);
            }
        });

        jLabel1.setText("Restaurant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel_hint)
                .addContainerGap(671, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton_Back)
                .addGap(144, 144, 144)
                .addComponent(jButton_Send)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Message)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_Restaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(jLabel_hint)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Restaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Message)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Send)
                    .addComponent(jButton_Back))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NutritionistWorkArea NutritionistWorkAreaatalogJPanel = (NutritionistWorkArea) component;
        NutritionistWorkAreaatalogJPanel.populateChildrenTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SendActionPerformed
        int s = jTable_Menu.getSelectedRow();
        if(s < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!");
            return;
        }        
        Menu menu = (Menu) jTable_Menu.getValueAt(s, 0);
        String message = jTextArea_Message.getText();
        RestaurantWorkRequest request = new RestaurantWorkRequest();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        request.setMenu(menu);
        RestaurantEnterprise restaurantEnterprise= (RestaurantEnterprise) jComboBox_Restaurant.getSelectedItem();
        restaurantEnterprise.getWorkQueue().getWorkRequestList().add(request);        
        account.getWorkQueue().getWorkRequestList().add(request);        
        JOptionPane.showMessageDialog(null, "Send Succeddful");

    }//GEN-LAST:event_jButton_SendActionPerformed

    private void jComboBox_RestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RestaurantActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) jComboBox_Restaurant.getSelectedItem();
        populateMenuTable((RestaurantEnterprise) enterprise);
    }//GEN-LAST:event_jComboBox_RestaurantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Send;
    private javax.swing.JComboBox jComboBox_Restaurant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Message;
    private javax.swing.JLabel jLabel_hint;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane_hospital;
    private javax.swing.JTable jTable_Menu;
    private javax.swing.JTable jTable_Restaurant;
    private javax.swing.JTextArea jTextArea_Message;
    // End of variables declaration//GEN-END:variables
}
