/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Nutritionist;

import business.Customer.Child;
import business.Enterprise.Enterprise;
import business.Health.Health;
import business.Health.VitalSign;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.Restaurant.RestaurantManagerWorkArea;

/**
 *
 * @author Chau_
 */
public class UpdateChildVitalSignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateChildVitalSignJPanel
     */
    private JPanel userProcessContainer;
    private Child child;
    public UpdateChildVitalSignJPanel(JPanel userProcessContainer, Child child) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.child = child;
        setMessage();
    }
    private void setMessage(){
        try {
            
            jTextField_BodyFatTend.setText(String.valueOf(child.getVitalSign().getBodyFatTend()));
            jTextField_BloodPressure.setText(String.valueOf(child.getVitalSign().getBloodPresser()));
            jTextField_Allergy.setText(child.getHealth().getAllergy());
            jTextField_Hearing.setText(child.getHealth().getHearing());
            jTextField_HeartRate.setText(String.valueOf(child.getVitalSign().getHeartRate()));
            jTextField_Sight.setText(String.valueOf(child.getHealth().getSight()));
            jTextField_Height.setText(String.valueOf(child.getHealth().getHeight()));
            jTextField_Weight.setText(String.valueOf(child.getHealth().getWeight()));
            jTextField_BMI.setText(String.valueOf(child.calculateBMI()));
            jButton_Save.setEnabled(true);
        } catch (Exception e) {
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_BloodPressure = new javax.swing.JLabel();
        jLabel_HeartRate = new javax.swing.JLabel();
        jLabel_HeadLine = new javax.swing.JLabel();
        jLabel_BMI = new javax.swing.JLabel();
        jLabel_BodyFatTend = new javax.swing.JLabel();
        jLabel_Height = new javax.swing.JLabel();
        jLabel_Weight = new javax.swing.JLabel();
        jLabel_Hearing = new javax.swing.JLabel();
        jLabel_Allergy = new javax.swing.JLabel();
        jLabelSight = new javax.swing.JLabel();
        jTextField_BloodPressure = new javax.swing.JTextField();
        jTextField_HeartRate = new javax.swing.JTextField();
        jTextField_BodyFatTend = new javax.swing.JTextField();
        jTextField_Height = new javax.swing.JTextField();
        jTextField_Weight = new javax.swing.JTextField();
        jTextField_Sight = new javax.swing.JTextField();
        jTextField_Allergy = new javax.swing.JTextField();
        jTextField_Hearing = new javax.swing.JTextField();
        jTextField_BMI = new javax.swing.JTextField();
        jButton_Update = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jButton_Cal = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();

        jLabel_BloodPressure.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_BloodPressure.setText("Blood Pressure:");

        jLabel_HeartRate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_HeartRate.setText("Heart Rate:");

        jLabel_HeadLine.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_HeadLine.setText("Update Child's VitalSign");

        jLabel_BMI.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_BMI.setText("BMI:");

        jLabel_BodyFatTend.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_BodyFatTend.setText("Body Fat Tend:");

        jLabel_Height.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Height.setText("Height:");

        jLabel_Weight.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Weight.setText("Weight:");

        jLabel_Hearing.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Hearing.setText("Hearing:");

        jLabel_Allergy.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Allergy.setText("Allergy:");

        jLabelSight.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSight.setText("Sight:");

        jTextField_BloodPressure.setEditable(false);

        jTextField_HeartRate.setEditable(false);

        jTextField_BodyFatTend.setEditable(false);

        jTextField_Height.setEditable(false);

        jTextField_Weight.setEditable(false);

        jTextField_Sight.setEditable(false);

        jTextField_Allergy.setEditable(false);

        jTextField_Hearing.setEditable(false);

        jTextField_BMI.setEditable(false);

        jButton_Update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Update.setText("Update VitalSign");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Save.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.setEnabled(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Cal.setText("Calculate BMI");
        jButton_Cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalActionPerformed(evt);
            }
        });

        jButton_Back.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Back.setText("<<Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel_HeadLine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_BloodPressure)
                                    .addComponent(jLabel_HeartRate))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_BloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_HeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_BodyFatTend)
                                    .addComponent(jLabel_Height)
                                    .addComponent(jLabel_Weight)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_BMI)
                                            .addComponent(jLabel_Hearing)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButton_Back)))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_Update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_Save))
                                    .addComponent(jTextField_BMI, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Height, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_BodyFatTend, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Sight, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Allergy, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Hearing, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jButton_Cal)))
                        .addGap(75, 139, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Allergy)
                            .addComponent(jLabelSight))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel_HeadLine)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BloodPressure)
                    .addComponent(jTextField_BloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_HeartRate)
                    .addComponent(jTextField_HeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_BodyFatTend)
                    .addComponent(jTextField_BodyFatTend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Height)
                    .addComponent(jTextField_Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Weight)
                    .addComponent(jTextField_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSight)
                    .addComponent(jTextField_Sight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Allergy)
                    .addComponent(jTextField_Allergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Hearing)
                    .addComponent(jTextField_Hearing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BMI)
                    .addComponent(jTextField_BMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Back)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_Save))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        jTextField_BodyFatTend.setEditable(true);
        jTextField_BloodPressure.setEditable(true);
        jTextField_Allergy.setEditable(true);
        jTextField_Hearing.setEditable(true);
        jTextField_HeartRate.setEditable(true);
        jTextField_Sight.setEditable(true);
        jTextField_Height.setEditable(true);
        jTextField_Weight.setEditable(true);
        jTextField_BMI.setEnabled(false);
        jButton_Save.setEnabled(true);
        
        
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        Health health = new Health();
        VitalSign vs = new VitalSign();
        health.setAllergy(jTextField_Allergy.getText());
        health.setHearing(jTextField_Height.getText());
        health.setHeight( Double.parseDouble(jTextField_Height.getText()));
        health.setSight( Double.parseDouble(jTextField_Hearing.getText()));
        health.setWeight(Double.parseDouble(jTextField_Weight.getText()));
        vs.setBloodPresser(Double.parseDouble(jTextField_BloodPressure.getText()));
        vs.setBodyFatTend(Double.parseDouble(jTextField_BodyFatTend.getText()));
        vs.setHeartRate(Double.parseDouble(jTextField_HeartRate.getText()));
        
        child.setHealth(health);
        child.setVitalSign(vs);
        JOptionPane.showMessageDialog(null, "Save Successfully");
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_CalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalActionPerformed
        // TODO add your handling code here:
        jTextField_BMI.setEditable(true);
        jTextField_BMI.setText(child.calculateBMI()+"");
        
        
    }//GEN-LAST:event_jButton_CalActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NutritionistWorkArea NutritionistWorkAreaatalogJPanel = (NutritionistWorkArea) component;
        NutritionistWorkAreaatalogJPanel.populateChildrenTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Cal;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabelSight;
    private javax.swing.JLabel jLabel_Allergy;
    private javax.swing.JLabel jLabel_BMI;
    private javax.swing.JLabel jLabel_BloodPressure;
    private javax.swing.JLabel jLabel_BodyFatTend;
    private javax.swing.JLabel jLabel_HeadLine;
    private javax.swing.JLabel jLabel_Hearing;
    private javax.swing.JLabel jLabel_HeartRate;
    private javax.swing.JLabel jLabel_Height;
    private javax.swing.JLabel jLabel_Weight;
    private javax.swing.JTextField jTextField_Allergy;
    private javax.swing.JTextField jTextField_BMI;
    private javax.swing.JTextField jTextField_BloodPressure;
    private javax.swing.JTextField jTextField_BodyFatTend;
    private javax.swing.JTextField jTextField_Hearing;
    private javax.swing.JTextField jTextField_HeartRate;
    private javax.swing.JTextField jTextField_Height;
    private javax.swing.JTextField jTextField_Sight;
    private javax.swing.JTextField jTextField_Weight;
    // End of variables declaration//GEN-END:variables
}
