/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Hospital;

import business.Business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.HospitalEnterprise;
import business.UserAccount.UserAccount;
import business.WorkQueue.HospitalWorkRequest;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Chau_
 */
public class HospitalWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalWorkArea
     */
    JPanel userProcessContainer;
    UserAccount account;
    HospitalEnterprise enterprise;
    EcoSystem business;
    
    public HospitalWorkArea(JPanel userProcessContainer,UserAccount account,Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise =(HospitalEnterprise)enterprise;
        this.business = business;
        populate();
        
    }
    
    public void populate(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headLineJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        jComboBox_Network = new javax.swing.JComboBox();
        jScrollPane_DaycareCenter = new javax.swing.JScrollPane();
        jTable_DayCareCenter = new javax.swing.JTable();
        jButton_GiveAdvice = new javax.swing.JButton();

        headLineJLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headLineJLabel.setText("Doctor Work Area");

        networkNameJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        networkNameJLabel.setText("NetWork Name:");

        jComboBox_Network.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox_Network.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NetworkActionPerformed(evt);
            }
        });

        jTable_DayCareCenter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable_DayCareCenter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City Name", "Daycare Center Name", "Number of Children", "Remarrks"
            }
        ));
        jScrollPane_DaycareCenter.setViewportView(jTable_DayCareCenter);

        jButton_GiveAdvice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_GiveAdvice.setText("Give Some Advice");
        jButton_GiveAdvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GiveAdviceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(headLineJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_DaycareCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(networkNameJLabel)
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox_Network, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_GiveAdvice)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(headLineJLabel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkNameJLabel)
                    .addComponent(jComboBox_Network, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane_DaycareCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton_GiveAdvice)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_NetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_NetworkActionPerformed

    private void jButton_GiveAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GiveAdviceActionPerformed
        // TODO add your handling code here:
       int selectedRow = jTable_DayCareCenter.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
         HospitalWorkRequest hospitalWorkRequest= (HospitalWorkRequest)jTable_DayCareCenter.getValueAt(selectedRow, 0);
     
        hospitalWorkRequest.setStatus("Processing");
        
        AdviceJPanel processWorkRequestJPanel = new AdviceJPanel(userProcessContainer, hospitalWorkRequest);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton_GiveAdviceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headLineJLabel;
    private javax.swing.JButton jButton_GiveAdvice;
    private javax.swing.JComboBox jComboBox_Network;
    private javax.swing.JScrollPane jScrollPane_DaycareCenter;
    private javax.swing.JTable jTable_DayCareCenter;
    private javax.swing.JLabel networkNameJLabel;
    // End of variables declaration//GEN-END:variables
}
