/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Hospital;

import business.Business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.HospitalEnterprise;
import business.Network.Network;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.HospitalWorkRequest;
import business.WorkQueue.WorkQueue;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chau_
 */
public class HospitalWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalWorkArea
     */
    JPanel userProcessContainer;
    UserAccount account;
    HospitalEnterprise enterprise;
    EcoSystem business;
    
    public HospitalWorkArea(JPanel userProcessContainer,UserAccount account,Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise =(HospitalEnterprise)enterprise;
        this.business = business;
        populateTable();
        
    }
    
//    public void populatedJComBox(){
//        jComboBox_Network.removeAll();
//              for (Network network : business.getNetworkList()){
//            jComboBox_Network.addItem(network);
//        }
//    }
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable_DayCareCenter.getModel();
        dtm.setRowCount(0);
        //nutritionis在request的时候，在本地network的hospital里面放了一个，在他自己的useraccount放了一个
        for(Network network : business.getNetworkList()){
            if(network == enterprise.getNetwork()){
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.DayCareInstitution)) {
                for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                    for(WorkRequest wr : o.getWorkQueue().getWorkRequestList()){
                        if(wr instanceof HospitalWorkRequest){
                            String s = ((HospitalWorkRequest) wr).message;
                                Object[] row = new Object[2];
                                row[0] = enterprise;
                                row[1] = s;
                                dtm.addRow(row);                      
                        }
                }
                }
                
            }
        }
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headLineJLabel = new javax.swing.JLabel();
        jScrollPane_DaycareCenter = new javax.swing.JScrollPane();
        jTable_DayCareCenter = new javax.swing.JTable();
        jButton_Send = new javax.swing.JButton();

        headLineJLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headLineJLabel.setText("Doctor Work Area");

        jTable_DayCareCenter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable_DayCareCenter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Daycare Center Name", "Message"
            }
        ));
        jScrollPane_DaycareCenter.setViewportView(jTable_DayCareCenter);

        jButton_Send.setText("jButton1");
        jButton_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(headLineJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane_DaycareCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Send)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(headLineJLabel)
                .addGap(122, 122, 122)
                .addComponent(jScrollPane_DaycareCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton_Send)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GiveAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GiveAdviceActionPerformed
        // TODO add your handling code here:
       int selectedRow = jTable_DayCareCenter.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
         HospitalWorkRequest hospitalWorkRequest= (HospitalWorkRequest)jTable_DayCareCenter.getValueAt(selectedRow, 0);
     
        hospitalWorkRequest.setStatus("Processing");
        
        AdviceJPanel processWorkRequestJPanel = new AdviceJPanel(userProcessContainer, hospitalWorkRequest);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton_GiveAdviceActionPerformed

    private void jButton_SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SendActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_DayCareCenter.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
         HospitalWorkRequest hospitalWorkRequest= (HospitalWorkRequest)jTable_DayCareCenter.getValueAt(selectedRow, 0);
     
        hospitalWorkRequest.setStatus("Processing");
        
        AdviceJPanel processWorkRequestJPanel = new AdviceJPanel(userProcessContainer, hospitalWorkRequest);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton_SendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headLineJLabel;
    private javax.swing.JButton jButton_Send;
    private javax.swing.JScrollPane jScrollPane_DaycareCenter;
    private javax.swing.JTable jTable_DayCareCenter;
    // End of variables declaration//GEN-END:variables
}
